name: release
on: push

jobs:
  release:
    name: 生成release
    runs-on: Ubuntu-20.04
    steps:
    - name: 检索文件
      uses: actions/checkout@v2

    - name: install
      run: npm install

    - name: 生成
      run: npx run semantic-release